version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - mcp-network

  backend:
    build: ./backend
    container_name: mcp-backend
    ports:
      - "8000:8000"
    volumes:
      - ./shared-data:/shared-data
    depends_on:
      - ollama
    networks:
      - mcp-network
    environment:
      - OLLAMA_HOST=ollama:11434

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react
    container_name: mcp-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mcp-network
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  ollama-data:

networks:
  mcp-network:
    driver: bridge
